spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB

file:
  loc: D:\\elasticSearch

elasticSearch:
  host: http://localhost:9200
  index: file_info
  select:
    query:
      path: /_search
  bulk:
    path: /_bulk
    file: bulk.json
  insert:
    file:
      path: /_doc?pipeline=attachment&refresh=true&pretty=true&routing=
  delete:
    query:
      path: /_delete_by_query