server:
  port: 18080

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  datasource:
    url: ENC(H92psafcerPEDN1saCUz0uCNfnVxfIAsCF58n/Z/chExOFDIXNg5c+AOuWiiVegnBZx5O4B8qAE=)
    username: ENC(NZ6yCBuTd3Phnz4ujuUVbr+FwY9GeRlp)
    password: ENC(lxll/AvbQLKHE6fYtwdEvcyUl5czZ+nx)
  jpa:
    database: postgresql
  config:
    import: common.yml

elasticSearch:
  host: http://192.168.0.100:9200
  index: file_info
  select:
    query:
      path: /_search
  bulk:
    path: /_bulk
    file: bulk.json
  insert:
    file:
      path: /_doc?pipeline=attachment&refresh=true&pretty=true&routing=
  delete:
    query:
      path: /_delete_by_query
  connectTimeout: 1000
  readTimeout: 1000
      
file:
  loc: /home/data